### ISSUE TITLE
Document new EventEmitter event format and data structures

### ISSUE THREAD

**Issue by hrharder** [ParadigmFoundation/ParadigmContracts#2]
## Overview
The new `EventEmitter` contract was pushed up [here](https://github.com/ParadigmFoundation/ParadigmContracts/blob/master/internal/contracts/event/EventEmitter.sol) with a single event that will be used as a dynamic event used to broadcast a variety of messages relevant for the OrderStream.

## Action items

Documentation is needed about the various types (first string parameters) and the structure of they byte arrays emitted for those different types.

- [ ] Produce spec for various event types

**Comment by Freydal** [comment]
The single event emitted from EventEmitter is defined as: `event ParadigmEvent(string eventType, bytes32[] data);`  The expected trigger of this event is through a call of the emitEvent function.  The function receives the eventType and data as parameters.  The parameter eventType is provided so that the event observer can have some information to determine how to decode the following arbitrary data.  The bytes32 array is intended to provide a generic format for an undefined amount of data output to be emitted.  The largest drawback to this method of data emission is the restrictions in converting dynamic length datatypes to bytes32 without having to take them apart.  A string for example is not fixed length. 

Example events can be seen [here](https://ropsten.etherscan.io/address/0x83E46fd49215543e13eeE0763c2a522E7d4F59eD#events). The events on this page aren't fully decoded.  They are mixed within some metadata.  
![image](https://user-images.githubusercontent.com/17073441/52285829-b2687200-292c-11e9-9b7a-f920ce2003b6.png)
The values of this example are as follows:
1. Start position of the first parameter.
1. Start position of the second parameter.
1. Length of the string. (Start of first parameter)
1. The string value for eventType.
1. Length of bytes32 values. (Start of second parameter)
1. First bytes32 value.
1. Second bytes32 value.
1. Third bytes32 value.

With the following example code you can see a web3 representation of the event above:
```javascript
eventEmitterABI = [
    {
      "inputs": [
        {
          "name": "auth",
          "type": "address"
        }
      ],
      "payable": false,
      "stateMutability": "nonpayable",
      "type": "constructor",
      "signature": "constructor"
    },
    {
      "anonymous": false,
      "inputs": [
        {
          "indexed": false,
          "name": "eventType",
          "type": "string"
        },
        {
          "indexed": false,
          "name": "data",
          "type": "bytes32[]"
        }
      ],
      "name": "ParadigmEvent",
      "type": "event",
      "signature": "0xb68836208a735161f1390dda0ff45fa887902bfcc41993796211c40b417ad48c"
    },
    {
      "constant": false,
      "inputs": [
        {
          "name": "eventType",
          "type": "string"
        },
        {
          "name": "data",
          "type": "bytes32[]"
        }
      ],
      "name": "emitEvent",
      "outputs": [],
      "payable": false,
      "stateMutability": "nonpayable",
      "type": "function",
      "signature": "0x27902401"
    }
  ];
eventEmitter = new web3.eth.Contract(eventEmitterABI, '0x83E46fd49215543e13eeE0763c2a522E7d4F59eD');
const events = await eventEmitter.getPastEvents('ParadigmEvent', { fromBlock: 0, toBlock: 4933649 });
const example  = events[2];
console.log(example.returnValues.eventType); // Output: ValidatorRegistryUpdate
console.log(example.returnValues.data.length); // Output: 3
```
**The trick now is to know how to decode the data in the the array.  Since this is internal it may be useful to provide default decoder javascript to support this.**

### ValidatorRegistryUpdate
```solidity
function emitValidatorRegistryUpdate(bytes32 tendermintPublicKey, address owner, uint stake) internal {
        bytes32[] memory data = new bytes32[](3);
        data[0] = tendermintPublicKey;
        data[1] = bytes32(uint(owner));
        data[2] = bytes32(stake);
        e.emitEvent("ValidatorRegistryUpdate", data);
    }
```
The function above is responsible for creating the bytes32 array that is emitted in this event.  The three response values are:
1. The tendermintPublicKey.  In solidity this is represented as bytes32 instead of base64 encoding.  This will need to be converted back to base 64.
1. The owner address.  The conversion directly to bytes32 from address was giving some bad results.  The conversion to uint prior to bytes32 resolved the issue.
1. The stake value.

An example of the processing this data may undergo to transform the data:
```javascript
const output = {
          tendermintPublicKey: example.returnValues.data[0],
          owner: web3.utils.numberToHex(web3.utils.hexToNumberString(example.returnValues.data[1])),
          stake: web3.utils.hexToNumberString(example.returnValues.data[2])
}
```

The tendermintPublicKey may undergo further transformation with the following **written for a node console**:
```javascript
output.tendermintPublicKey = Buffer.from(output.tendermintPublicKey.substr(2),'hex').toString('base64')
```
 
## Shortcomings
* There needs to be a place or utility to decode events.
